language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
before_deploy: rm -rf .eggs
deploy:
  provider: pypi
  user: matfire
  password: Galako999
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.6" 
