language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
before_deploy: rm -rf .eggs
deploy:
  provider: pypi
  user: matfire
  password:
    secure: dPiS42PN0gZA67lRlcKehsQvjSoRpXQDOtS5iGIz7tmQjG8cYLEP+vDdwSIMmi5QkR/3lBTTEmiaq6N25bMTsgQyT91zFgvtrpdH1cT6xix+Ytu5WtZrevcpfdWsdl2HxbpWjEmSgh9MzobAJdXSWWkZwa1DBI9YCa8iDntBPRXy5Dt9SKfVFxi5hFPhe4vntbRE9t3Vx4NKQLqFNSLUVtgtWJDcFz07XbCyxHpa3Dq0H3pFDBUyeTkUxsIEOW1VSp2w9ddET6tXie3vkDZqVjsnzLK3HDt/VUKSujahEDviJh2xAvKVtubmNbYoYbmqN8qeAL3iJpFVvYNyQ4rdw1fYnoAtvioNr+72RbLNOfe9UjNX2xwni39qsQbez6J9a7tgF0VBDNfV90zZxHUtE+gCH9A9dzV/PtjrZFwlypF1K+fxiljjO8foI3KEdj76K5DQcKstRsvpyPUQNtq3iuuX3ekMwQt6ADNrYpr2PPmywnNMWQVI6ui91CLvnknpT2FVJuwYKmlwk3+dsHO85RGWnxe7nE1rtkHvvMF7wwKJ3f+3tra8QmL/y9FcSh/spL73Ptztk2L3VTuO6+KjDdinGT9ZL0rA17vfhkouGwmUqLsgJgA8h6TR6wPO926EtdWyEpyDk31QZnakeJNnxWvyVaCwIXg91ZUMhtrGBQ8=
  on:
    tags: true
