language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  user: matfire
  password:
    secure: Akyjfb0+sfExKaX4RlqBtYdlVbWUEGnlzq6wyFBelBuKRSooDA0PNrEuKijHjubU3GVE77498RvRg2s57IegfzuTDktEq6l1jGNFit2tjo1f0+c6UovO3WAzZz9bdwU5X+vxSMccHPxLE0o73+8l3nQCoKpumlTTZqlWjj1X7kACkpjFOeWOCXe7g6gIek1Ju7ZqcVKOpn9Cl1nPyX/3NOfP+tvvUh7VH4EpxjvRKXkvCmJ3e4BVNkiu5q1Mx1WkrPysNKwMp7Xj85q5pOKbe+gFveJjtu/eBxW6oGmERAr+Y0UxYcxn0g5ePHB12m8XbUpyTD4zAXC9pDLa0+KoXtBVshDETgk42CGs/QueQ77aS91lyxY8yT9RVLku+d5Q178oo1hr0lWYboSGGqmUu57hwm6PD5/8deLRkW42jolBHHwIMskS7GAuNaKFsHj21ro41TNUIM/9yBy/v3ELtUeaMVe4Xe3ehXJtTgrfIxw5zv+V61GcYU/9S1+8wzK8jTUFINpsdQsZnUIflth5rMV0/NL5heIxCfPdZmNYZnbh433qIH/S+YuZL6kOR20XJgoc0ftuiUji7VCpmXOFRg9sgdvh+wa0/kDEfVk+8xUGOkMqFDoeV4Rs97xo1sYPEFkab5DBZFtzehS0CHrsV51IOceoupo1V8AJ3BePXTU=
  on:
    tags: true
